###################################################################################################

- name: redhat | dependencies

  become: true

  with_items: '{{ cron_dependencies }}'

  yum : name={{ item }} state=present

  tags:
    - artemis
    - platform
    - cron
    - daemon
    - redhat

###################################################################################################
