###################################################################################################

- name: import | family

  when: os_family_is_redhat

  include_vars: '{{ os_family_lower }}{{ yaml_file_extension }}'

  tags:
    - artemis
    - boot
    - initramfs

###################################################################################################

- name: import | overrides

  when: overrides_verified

  include_vars: '{{ overrides_path }}'

  tags:
    - artemis
    - boot
    - initramfs

###################################################################################################

- name: family

  when: os_family_is_redhat

  include: '{{ os_family_lower }}{{ yaml_file_extension }}'
  static : false

  tags:
    - artemis
    - boot
    - initramfs

###################################################################################################

- name: update

  when: initramfs_update

  become: true

  command: '{{ initramfs_update_cmd }}'

  register: update

  tags:
    - artemis
    - boot
    - initramfs

###################################################################################################

- name: signals

  when: update.changed

  set_fact:
    initramfs_update: false
    bounce          : true

  tags:
    - artemis
    - boot
    - initramfs

###################################################################################################
