###################################################################################################

- name: redhat | dependencies

  become: true

  with_items: '{{ initramfs_dependencies }}'

  yum : name={{ item }} state=present

  tags:
    - artemis
    - boot
    - initramfs
    - redhat

###################################################################################################
