###################################################################################################

- name: redhat | dependencies

  become: true

  with_items: '{{ grub_dependencies }}'

  yum : name={{ item }} state=present

  tags:
    - artemis
    - boot
    - grub
    - redhat

###################################################################################################
