###################################################################################################

- name: configure

  become     : true
  become_user: '{{ ssh_user }}'

  template: src={{ ssh_config_src  }}
           dest={{ ssh_config_dest }}
           mode={{ ssh_config_mode }}

  tags:
    - artemis
    - platform
    - ssh
    - client

###################################################################################################
