###################################################################################################

- name: import | family

  when: os_family_is_debian

  include_vars: '{{ os_family_lower }}{{ yaml_file_extension }}'

  tags:
    - artemis
    - platform
    - sysstat

###################################################################################################

- name: import | overrides

  when: overrides_verified

  include_vars: '{{ overrides_path }}'

  tags:
    - artemis
    - platform
    - sysstat

###################################################################################################

- name: family

  when: os_family_is_debian
     or os_family_is_redhat

  include: '{{ os_family_lower }}{{ yaml_file_extension }}'
  static : false

  tags:
    - artemis
    - platform
    - sysstat

###################################################################################################
