###################################################################################################

- name: import | family

  when: os_family_is_debian
     or os_family_is_redhat

  include_vars: '{{ os_family_lower }}{{ yaml_file_extension }}'

  tags:
    - artemis
    - platform
    - mac

###################################################################################################

- name: import | overrides

  when: overrides_verified

  include_vars: '{{ overrides_path }}'

  tags:
    - artemis
    - platform
    - mac

###################################################################################################

- name: verify

  assert:
    that:

      - mac_security is not none
      - mac_security | length > 0

  tags:
    - artemis
    - platform
    - mac

###################################################################################################

- name: debian

  when: os_family_is_debian

  include: debian.yml
  static : false

  tags:
    - artemis
    - platform
    - mac
    - debian

###################################################################################################

- name: redhat

  when: os_family_is_redhat

  include: redhat.yml
  static : false

  tags:
    - artemis
    - platform
    - mac
    - redhat

###################################################################################################
