###################################################################################################

- name: keys | trust

  become: true

  with_items: '{{ package_apt_keys }}'

  apt_key: data='{{ item }}'

  tags:
    - artemis
    - platform
    - package
    - apt
    - keys

###################################################################################################
