###################################################################################################

- name: debian | dependencies

  become: true

  with_items: '{{ logrotate_dependencies }}'

  apt : name={{ item }} state=present install_recommends=false

  tags:
    - artemis
    - logging
    - logrotate
    - debian

###################################################################################################
