###################################################################################################

- name: redhat | dependencies

  become: true

  with_items: '{{ logrotate_dependencies }}'

  yum : name={{ item }} state=present

  tags:
    - artemis
    - logging
    - logrotate
    - redhat

###################################################################################################
