###################################################################################################

- name: configure

  become: true

  template: src={{ managed_src  }}
           dest={{ managed_dest }}

  changed_when: false

  tags:
    - artemis
    - platform
    - managed

###################################################################################################
