###################################################################################################

- name: debian | dependencies

  become: true

  with_items: '{{ btrfs_dependencies }}'

  apt : name={{ item }} state=present install_recommends=false

  tags:
    - artemis
    - filesystem
    - btrfs
    - debian

###################################################################################################
