###################################################################################################

- name: redhat | dependencies

  become: true

  with_items: '{{ btrfs_dependencies }}'

  yum : name={{ item }} state=present

  tags:
    - artemis
    - filesystem
    - btrfs
    - redhat

###################################################################################################
