###################################################################################################

- name: balance

  become: true

  command: '{{ btrfs_balance_command }} {{ btrfs_mount }}'

  tags:
    - artemis
    - filesystem
    - btrfs

###################################################################################################
