###################################################################################################

- name : bounce

  hosts: all

  gather_facts: false

  roles:

    -   role: bootstrap

    - { role: platform/bounce, bounce: true }

  tags:
    - artemis
    - platform
    - bounce

###################################################################################################
