###################################################################################################

- name: debian | dependencies

  become: true

  with_items: '{{ lvm_dependencies }}'

  apt : name={{ item }} state=present install_recommends=false

  tags:
    - artemis
    - volume
    - lvm
    - common
    - debian

###################################################################################################
