###################################################################################################

- name: debian

  when: os_family_is_debian

  include: debian.yml
  static : false

  tags:
    - artemis
    - volume
    - lvm
    - common
    - debian

###################################################################################################

- name: redhat

  when: os_family_is_redhat

  include: redhat.yml
  static : false

  tags:
    - artemis
    - volume
    - lvm
    - common
    - redhat

###################################################################################################
