###################################################################################################

- name: family

  when: os_family_is_debian
     or os_family_is_redhat

  include: '{{ os_family_lower }}{{ yaml_file_extension }}'
  static : false

  tags:
    - artemis
    - volume
    - lvm
    - common

###################################################################################################
