###################################################################################################

- name: redhat | dependencies

  become: true

  with_items: '{{ lvm_dependencies }}'

  yum : name={{ item }} state=present

  tags:
    - artemis
    - volume
    - lvm
    - common
    - redhat

###################################################################################################
