###################################################################################################

- name : halt

  hosts: all

  gather_facts: false

  roles:

    - role: bootstrap

    - role: platform/halt

  tags:
    - artemis
    - platform
    - halt

###################################################################################################
